### ISSUE TITLE
cant patch 

### ISSUE THREAD

**Issue by GramingFoxTeam** [MarmoriPelaa/GTPatcher-Android#3]
![image](https://user-images.githubusercontent.com/29177546/78679759-4e0bbe80-78f3-11ea-83ba-89f0135d4075.png)
i dont know why it doesnt works.

**Comment by MarmoriPelaa** [comment]
Download the latest version. It should be fixed now.

**Comment by GramingFoxTeam** [comment]
> Download the latest version. It should be fixed now.

Ok it worked!Thanks
